
name: Clone Public Repository Workflow

on:
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
    
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'MCaveMan'
          repository: 'andy_public'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd andy_public
          ls -la
